fvrIcons: [backburger,city,cog,directions,goback,home,information,link,menu,github,facebook,instagram,twitter,donate,ishare,natureman,together,voice,walk]
pageIncludes: [pages]
mapIncludes: [trails,markers]
